# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\"c\n\rMissionUpdate\x12\x13\n\x0bOperator_ID\x18\x01 \x01(\t\x12\x0e\n\x06UAS_ID\x18\x02 \x01(\t\x12\r\n\x05Start\x18\x03 \x01(\x01\x12\x0b\n\x03\x45nd\x18\x04 \x01(\x01\x12\x11\n\tKeyCommit\x18\x05 \x01(\t\"@\n\x0bRequestData\x12\x13\n\x0bOperator_ID\x18\x01 \x01(\t\x12\x0e\n\x06UAS_ID\x18\x02 \x01(\t\x12\x0c\n\x04Time\x18\x03 \x01(\x01\"-\n\tReplyData\x12\x11\n\tKeyCommit\x18\x01 \x01(\t\x12\r\n\x05Start\x18\x02 \x01(\x01\"\x1e\n\tSendError\x12\x11\n\tErrorCode\x18\x01 \x01(\x05\x62\x06proto3'
)




_MISSIONUPDATE = _descriptor.Descriptor(
  name='MissionUpdate',
  full_name='MissionUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Operator_ID', full_name='MissionUpdate.Operator_ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UAS_ID', full_name='MissionUpdate.UAS_ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Start', full_name='MissionUpdate.Start', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='End', full_name='MissionUpdate.End', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KeyCommit', full_name='MissionUpdate.KeyCommit', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=117,
)


_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Operator_ID', full_name='RequestData.Operator_ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UAS_ID', full_name='RequestData.UAS_ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Time', full_name='RequestData.Time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=183,
)


_REPLYDATA = _descriptor.Descriptor(
  name='ReplyData',
  full_name='ReplyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='KeyCommit', full_name='ReplyData.KeyCommit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Start', full_name='ReplyData.Start', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=230,
)


_SENDERROR = _descriptor.Descriptor(
  name='SendError',
  full_name='SendError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrorCode', full_name='SendError.ErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=262,
)

DESCRIPTOR.message_types_by_name['MissionUpdate'] = _MISSIONUPDATE
DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['ReplyData'] = _REPLYDATA
DESCRIPTOR.message_types_by_name['SendError'] = _SENDERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MissionUpdate = _reflection.GeneratedProtocolMessageType('MissionUpdate', (_message.Message,), {
  'DESCRIPTOR' : _MISSIONUPDATE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:MissionUpdate)
  })
_sym_db.RegisterMessage(MissionUpdate)

RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATA,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:RequestData)
  })
_sym_db.RegisterMessage(RequestData)

ReplyData = _reflection.GeneratedProtocolMessageType('ReplyData', (_message.Message,), {
  'DESCRIPTOR' : _REPLYDATA,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ReplyData)
  })
_sym_db.RegisterMessage(ReplyData)

SendError = _reflection.GeneratedProtocolMessageType('SendError', (_message.Message,), {
  'DESCRIPTOR' : _SENDERROR,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:SendError)
  })
_sym_db.RegisterMessage(SendError)


# @@protoc_insertion_point(module_scope)
